from protocol import FRAME_HEADER_1, PACKET_LEN as TELEMETRY_PACKET_LEN


DEFAULT_PORT = "COM3"
DEFAULT_BAUD = 115200

FRAME_START = FRAME_HEADER_1
PACKET_LEN = TELEMETRY_PACKET_LEN

STATUS_TEST = 1 << 0
STATUS_IDLE = 1 << 1
STATUS_FLIGHT = 1 << 2
STATUS_DESCENT = 1 << 3
STATUS_RECOVERY = 1 << 4

STATUS_ERROR_SENSOR = 1 << 5
STATUS_ERROR_LOW_BAT = 1 << 6
STATUS_ERROR_CRITICAL = 1 << 7

LORA_TIMEOUT_SEC = 2.0
