; PlatformIO Project Configuration File

[env:esp32-s3-devkitc-1-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_mode = qio
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

upload_port = /dev/cu.wchusbserial*
monitor_port = /dev/cu.wchusbserial*
upload_speed = 115200
monitor_speed = 115200

lib_deps =
	sandeepmistry/LoRa @ ^0.8.0

build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D ARDUINO_USB_MSC_ON_BOOT=0
	-D ARDUINO_USB_DFU_ON_BOOT=0
	-D CORE_DEBUG_LEVEL=0

build_unflags =
	-D ARDUINO_USB_CDC_ON_BOOT=1
